crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('objects.urls')),
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^compare/$', views.compare, name='compare'),
    url(r'^accounts/$', views.accounts, name='accounts'),
    url(r'^accounts/create/$', views.account_create, name='account_create'),
    url(r'^accounts/(?P<aid>[0-9]+)/$', views.account, name='account'),
    url(r'^accounts/(?P<aid>[0-9]+)/edit/$', views.account_update, name='account_update'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^contacts/(?P<cid>[0-9]+)/$', views.contact, name='contact'),
    url(r'^contacts/create/$', views.contact_create, name='contact_create'),
    url(r'^contacts/(?P<cid>[0-9]+)/edit/$', views.contact_update, name='contact_update'),
    url(r'^leads/(?P<lid>[0-9]+)/$', views.lead, name='lead'),
    url(r'^leads/(?P<lid>[0-9]+)/edit/$', views.lead_update, name='lead_update'),
    url(r'^leads/$', views.leads, name='leads'),
    url(r'^leads/create/$', views.lead_create, name='lead_create'),
    url(r'^opportunities/(?P<oid>[0-9]+)/$', views.opportunity, name='opportunity'),
    url(r'^opportunities/$', views.opportunities, name='opportunities'),
    url(r'^opportunities/create/$', views.opportunity_create, name='opportunity_create'),
    url(r'^opportunities/(?P<oid>[0-9]+)/edit/$', views.opportunity_update, name='opportunity_update'),
    url(r'^chart1/$', views.chart1, name='chart1'),
    url(r'^chart2/$', views.chart2, name='chart2'),
    url(r'^chart3/$', views.chart3, name='chart3')
]

web/templates/web/account.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block title %}Accounts{% endblock %}
{% block account_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <div class="card container-fluid" style="margin-top: 1em">
                    {% if error_message %}
                        <h3>Error!</h3>
                        <p>{{ error_message }}</p>
                    {% endif %}
                    {% if not error_message %}
                        <h3>{{ name }}</h3>
                        <div style="position: absolute; right: 2em;margin-top: 0.5em;">
                            <a href="edit/" class="btn btn-primary" title="Edit account" id="editbtn"><i class="fa fa-pencil"></i></a>
                            <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" title="Delete record" id="del"><i class="fa fa-trash"></i></button>
                        </div>
                        <div class="card-body">
                            <strong>Phone:</strong> {{ phone }}<br>
                            <strong>Website:</strong> <a href="{{ website }}">{{ website }}</a><br>
                            {% if parent != None %}
                                <strong>Parent:</strong> <a href="/accounts/{{ parent.id }}">{{ parent.name }}</a><br>
                            {% endif %}
                            {% if locations %}
                                <strong>Locations:</strong> <br>
                                <ul>
                                {% for loc in locations %}
                                    <li>{{ loc.place }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                            <strong>Added by:</strong> {{ owner }}
                            <br>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-4">
                {% if not error_message %}
                    <div class="card container-fluid" style="margin-top: 1em">
                        <h3>Contacts</h3>
                        <div class="card-body">
                            {% if not contacts %}
                                <p>No contacts found for this company. Add one now.</p>
                            {% else %}
                                {% for obj in contacts %}
                                    Name: <a href="{% url 'web:contact' obj.id %}">{{ obj.name }}</a><br>
                                    Phone: {{ obj.phone_number }}<br>
                                    Email: <a href="mailto:{{ obj.email }}">{{ obj.email }}</a>
                                    <hr>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-sm-4">
                {% if not error_message %}
                    <div class="card container-fluid" style="margin-top: 1em">
                        <h3>Opportunities</h3>
                        <div class="card-body">
                            {% if not opportunities %}
                                <p>No opportunities to show. Create one now.</p>
                            {% else %}
                                {% for obj in opportunities %}
                                    Name: <a href="/opportunities/{{ obj.id }}/">{{ obj.name }}</a><br>
                                    Stage: {{ obj.stage }}<br>
                                    Close Date: {{ obj.close_date }}<br>
                                    <hr>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirmation</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this record?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" id="delcnf">Yes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block js_scripts %}
    <script src="{% static 'js/delete.js' %}"></script>
    <script>

        function loadUrl(location) {
            this.document.location.href = location;
        }

        $('#delcnf').click(function(){
            deleteObj('/api/del_acc/{{ id }}/');
            loadUrl(window.location.origin + '/accounts/');
        });
    </script>
{% endblock %}

web/templates/web/accounts.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block title %}Accounts{% endblock %}
{% block account_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <div class="card" style="margin-top: 1em">
                    <div class="card-body">
                        <i class="fa fa-building" style="font-size:48px;"></i>
                        <div style="display: inline-block">
                            <h4 class="page-titles">Accounts</h4>
                        </div>
                        <br>
                        <br>
                        <div class="input-group">
                            Search
                            <div class="input-group col-sm-3">
                                <input type="search" class="form-control" id="searchip">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button" id="searchbtn"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </span>
                            </div>
                            <a href="{% url 'web:account_create' %}" class="btn btn-success" title="Add a new account" id="addbtn" style="position: absolute;right: 2%"><i class="fa fa-plus"></i></a>
                        </div>
                        <br>
                        {# The table comes here #}
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Website</th>
                                    <th>Phone</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <div style="position: absolute; right: 2%;">
                            <button type="button" class="btn btn-primary" id="prev"><i class="fa fa-arrow-left"></i>&nbsp;Previous</button>
                            &nbsp;
                            <input type="text" placeholder="Index..." size="10%" id="pgidx">
                            &nbsp;
                            <button type="button" class="btn btn-primary" id="next">Next&nbsp;<i class="fa fa-arrow-right"></i></button>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_scripts %}
    <script src="{% static 'js/compareChart.js' %}"></script>
    <script>

        var start = 0;
        var end = start + 10;


        function tryParseJSON (jsonString){
            try {
                var o = JSON.parse(jsonString);
                if (o && typeof o === "object") {
                    return o;
                }
            }
            catch (e) { }
            return false;
        }


        function getTable(start, end) {
            // Get checkbox value here.
            // And also the my accounts only checkbox
            var dtype = 'json';
            var xhttp = XMLReq(fillTable);
            var local = window.location.origin;
            xhttp.open("GET", local + '/api/accounts/' + dtype + '/' + start + '/' + end, true);
            xhttp.send();
        }


        function fillTable(data) {
            var parsed = tryParseJSON(data);
            if (parsed === false) {
                //It's not JSON. It's something.
            }

            else {
                for (var obj in parsed) {
                    var ob = parsed[obj];
                    var pk = ob['pk'];
                    var fields = ob['fields'];
                    var name = fields['name'];
                    var website = fields['website'];
                    var phone = fields['phone_number'];
                    var owner = fields['owner'];
                    var added_on = fields['added_on'];
                    var subsidiary_of = fields['subsidiary_of'];
                    // Now add the table. :)
                    var markup = "<tr><td>" + (start + parseInt(obj) + 1) + "</td><td>" +'<a href="/accounts/' + pk + '">' +
                        name + '</a>' + "</td><td>" + website +"</td><td>"+ phone + "</td></tr>";
                    $('table tbody').append(markup);
                }
            }
        }
        getTable(0,10);

        $('#prev').click(function () {
            start = start - 10;
            if (start < 0) {
                start = 0;
            }
            end = start + 10;
            $('table tbody tr').remove();
            getTable(start,end);
        });

        $('#next').click(function () {
            start = start + 10;
            end = start + 10;
            $('table tbody tr').remove();
            getTable(start,end);
        });

        $("#pgidx").keypress(function(event) {
            if (event.which === 13) {
                event.preventDefault();
                start = parseInt($('#pgidx').val()) - 1;
                if (start < 0) {
                    start = 0;
                }
                end = start + 10;
                $('table tbody tr').remove();
                getTable(start,end);
            }
        });

        $("#searchbtn").click(function () {
            var term = $("#searchip").val();
            search(term);
        });


        $("#searchip").keypress(function (event) {
            if (event.which === 13) {
                event.preventDefault();
                var term = $("#searchip").val();
                search(term);
            }
        });

        function search(term) {
            var xhttp = XMLReq(fillTable);
            var local = window.location.origin;
            xhttp.open("GET", local + '/api/sch_acc/?q=' + term, true);
            $('table tbody tr').remove();
            xhttp.send();
        }
    </script>
{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CRM{% endblock %}</title>
    {# Loading the static files #}
    {% load staticfiles %}
    {# The custom css file to load #}
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    {# The favicon #}
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-arrow-buttons.css' %}">
</head>
<body>
    {# The navbar, https://getbootstrap.com/docs/4.0/components/navbar/  #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'web:index' %}">CRM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav-pills navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link {% block compare_active %}{% endblock %}" href="{% url 'web:compare' %}">Compare</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block account_active %}{% endblock %}" href="{% url 'web:accounts' %}">Accounts</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block contact_active %}{% endblock %}" href="{% url 'web:contacts' %}">Contacts</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block lead_active %}{% endblock %}" href="{% url 'web:leads' %}">Leads</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link {% block opportunity_active %}{% endblock %}" href="{% url 'web:opportunities' %}">Opportunities</a>
                </li>
            </ul>
            <ul class="nav-pills navbar-nav mr-auto"></ul>
            <ul class="nav-pills navbar-nav">
                {# A search bar is coming here.. #}
{#                <li class="nav-item">#}
                    {# So many hacks for this #}
{#                    <div style="color: white; display: table;">#}
{#                        <div style="display: table-cell; vertical-align: middle;">#}
{#                            &nbsp;XML&nbsp;#}
{#                        </div>#}
{#                        <div style="display: table-cell; vertical-align: middle;">#}
{#                            <label class="switch">#}
{#                                <input type="checkbox" id="jsonswitch">#}
{#                                <span class="slider round"></span>#}
{#                            </label>#}
{#                        </div>#}
{#                        <div style="display: table-cell; vertical-align: middle;">#}
{#                            &nbsp;JSON&nbsp;&nbsp;#}
{#                        </div>#}
{#                    </div>#}
{#                </li>#}
                {% if request.user.is_authenticated == 0 %}
                    <li class="nav-item active">
                        <a class="nav-link active" href="{% url 'web:login_user' %}"><i class="fa fa-power-off"></i>&nbsp; Log In</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'web:logout_user' %}"><i class="fa fa-power-off"></i>&nbsp; Log out</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js_scripts %}
{% endblock %}
</html>

web/templates/web/contacts.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block title %}Contacts{% endblock %}
{% block contact_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <div class="card" style="margin-top: 1em">
                    <div class="card-body">
                        <i class="fa fa-user" style="font-size:48px;"></i>
                        <div style="display: inline-block">
                            <h4 class="page-titles">Contacts</h4>
                        </div>
                        <br>
                        <br>
                        <div class="input-group">
                            Search
                            <div class="input-group col-sm-3">
                                <input type="search" class="form-control" id="searchip">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button" id="searchbtn"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </span>
                            </div>
                            <a href="{% url 'web:contact_create' %}" class="btn btn-success" title="Add a new contact" id="addbtn" style="position: absolute;right: 2%"><i class="fa fa-plus"></i></a>
                        </div>
                        <br>
                        {# The table comes here #}
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <div style="position: absolute; right: 2%;">
                            <button type="button" class="btn btn-primary" id="prev"><i class="fa fa-arrow-left"></i>&nbsp;Previous</button>
                            &nbsp;
                            <input type="text" placeholder="Index..." size="10%" id="pgidx">
                            &nbsp;
                            <button type="button" class="btn btn-primary" id="next">Next&nbsp;<i class="fa fa-arrow-right"></i></button>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_scripts %}
    <script src="{% static 'js/compareChart.js' %}"></script>
    <script>

        var start = 0;
        var end = start + 10;


        function tryParseJSON (jsonString){
            try {
                var o = JSON.parse(jsonString);
                if (o && typeof o === "object") {
                    return o;
                }
            }
            catch (e) { }
            return false;
        }


        function getTable(start, end) {
            // Get checkbox value here.
            // And also the my accounts only checkbox
            var dtype = 'json';
            var xhttp = XMLReq(fillTable);
            var local = window.location.origin;
            xhttp.open("GET", local + '/api/contacts/' + dtype + '/' + start + '/' + end, true);
            xhttp.send();
        }


        function fillTable(data) {
            var parsed = tryParseJSON(data);
            if (parsed === false) {
                //It's not JSON. It's something.
            }

            else {
                for (var obj in parsed) {
                    var ob = parsed[obj];
                    var pk = ob['pk'];
                    var fields = ob['fields'];
                    var name = fields['name'];
                    var email = fields['email'];
                    var phone = fields['phone_number'];
                    // Now add the table. :)
                    var markup = "<tr><td>" + (start + parseInt(obj) + 1) + "</td><td>" +'<a href="/contacts/' + pk + '">' +
                        name + '</a>' + "</td><td>" + email +"</td><td>"+ phone + "</td></tr>";
                    $('table tbody').append(markup);
                }
            }
        }
        getTable(0,10);

        $('#prev').click(function () {
            start = start - 10;
            if (start < 0) {
                start = 0;
            }
            end = start + 10;
            $('table tbody tr').remove();
            getTable(start,end);
        });

        $('#next').click(function () {
            start = start + 10;
            end = start + 10;
            $('table tbody tr').remove();
            getTable(start,end);
        });

        $("#pgidx").keypress(function(event) {
            if (event.which === 13) {
                event.preventDefault();
                start = parseInt($('#pgidx').val()) - 1;
                if (start < 0) {
                    start = 0;
                }
                end = start + 10;
                $('table tbody tr').remove();
                getTable(start,end);
            }
        });

        $("#searchbtn").click(function () {
            var term = $("#searchip").val();
            search(term);
        });


        $("#searchip").keypress(function (event) {
            if (event.which === 13) {
                event.preventDefault();
                var term = $("#searchip").val();
                search(term);
            }
        });

        function search(term) {
            var xhttp = XMLReq(fillTable);
            var local = window.location.origin;
            xhttp.open("GET", local + '/api/sch_ctc/?q=' + term, true);
            $('table tbody tr').remove();
            xhttp.send();
        }

    </script>
{% endblock %}

web/templates/web/leads.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block title %}Leads{% endblock %}
{% block lead_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <div class="card" style="margin-top: 1em">
                    <div class="card-body">
                            <i class="fa fa-tasks" style="font-size:48px;"></i>
                        <div style="display: inline-block">
                            <h4 class="page-titles">Leads</h4>
                        </div>
                        <br>
                        <br>
                        <div class="input-group">
                            Search
                            <div class="input-group col-sm-3">
                                <input type="search" class="form-control" id="searchip">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button" id="searchbtn"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </span>
                            </div>
                            <a href="{% url 'web:lead_create' %}" class="btn btn-success" title="Add a new lead" id="addbtn" style="position: absolute;right: 2%"><i class="fa fa-plus"></i></a>
                        </div>
                        <br>
                        {# The table comes here #}
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <div style="position: absolute; right: 2%;">
                            <button type="button" class="btn btn-primary" id="prev"><i class="fa fa-arrow-left"></i>&nbsp;Previous</button>
                            &nbsp;
                            <input type="text" placeholder="Index..." size="10%" id="pgidx">
                            &nbsp;
                            <button type="button" class="btn btn-primary" id="next">Next&nbsp;<i class="fa fa-arrow-right"></i></button>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_scripts %}
    <script src="{% static 'js/compareChart.js' %}"></script>
    <script>

        var start = 0;
        var end = start + 10;


        function tryParseJSON (jsonString){
            try {
                var o = JSON.parse(jsonString);
                if (o && typeof o === "object") {
                    return o;
                }
            }
            catch (e) { }
            return false;
        }


        function getTable(start, end) {
            // Get checkbox value here.
            // And also the my accounts only checkbox
            var dtype = 'json';
            var xhttp = XMLReq(fillTable);
            var local = window.location.origin;
            xhttp.open("GET", local + '/api/leads/' + dtype + '/' + start + '/' + end, true);
            xhttp.send();
        }


        function fillTable(data) {
            var parsed = tryParseJSON(data);
            if (parsed === false) {
                //It's not JSON. It's something.
            }

            else {
                for (var obj in parsed) {
                    var ob = parsed[obj];
                    var pk = ob['pk'];
                    var fields = ob['fields'];
                    var name = fields['name'];
                    var email = fields['email'];
                    var status = fields['status'];

                    if (status === 1) {
                        status = 'Open - Not Contacted';
                    }
                    else if (status === 2) {
                        status = 'Working - Contacted';
                    }
                    else if (status === 3) {
                        status = 'Closed - Not Converted';
                    }
                    else {
                        status = 'Converted';
                    }


                    // Now add the table. :)
                    var markup = "<tr><td>" + (start + parseInt(obj) + 1) + "</td><td>" +'<a href="/leads/' + pk + '">' +
                        name + '</a>' + "</td><td>" + email +"</td><td>"+ status + "</td></tr>";
                    $('table tbody').append(markup);
                }
            }
        }
        getTable(0,10);

        $('#prev').click(function () {
            start = start - 10;
            if (start < 0) {
                start = 0;
            }
            end = start + 10;
            $('table tbody tr').remove();
            getTable(start,end);
        });

        $('#next').click(function () {
            start = start + 10;
            end = start + 10;
            $('table tbody tr').remove();
            getTable(start,end);
        });

        $("#pgidx").keypress(function(event) {
            if (event.which === 13) {
                event.preventDefault();
                start = parseInt($('#pgidx').val()) - 1;
                if (start < 0) {
                    start = 0;
                }
                end = start + 10;
                $('table tbody tr').remove();
                getTable(start,end);
            }
        });

        $("#searchbtn").click(function () {
            var term = $("#searchip").val();
            search(term);
        });


        $("#searchip").keypress(function (event) {
            if (event.which === 13) {
                event.preventDefault();
                var term = $("#searchip").val();
                search(term);
            }
        });

        function search(term) {
            var xhttp = XMLReq(fillTable);
            var local = window.location.origin;
            xhttp.open("GET", local + '/api/sch_lead/?q=' + term, true);
            $('table tbody tr').remove();
            xhttp.send();
        }
    </script>
{% endblock %}

web/templates/web/login.html
{% extends 'web/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'web:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}